apiVersion: v1
kind: Service
metadata:
  name: happy-school-postgres
  namespace: happy-school
  labels:
    app: happy-school-postgres
spec:
  selector:
    app: happy-school-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  # ClusterIP: solo accesible dentro del cluster (no expuesto al exterior)
  type: ClusterIP
